reet-place.app.version: v.0.0.1

logging:
  level:
    com.dnd.reetplace: debug
    org.hibernate.SQL: debug

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

---
# Settings for local(dev)
management.endpoints.web.exposure.include: "*"

spring:
  config.activate.on-profile: local
  redis:
    host: localhost
    port: 6379
  datasource:
    url: ${REET_PLACE_LOCAL_DB_URL}
    username: ${REET_PLACE_LOCAL_DB_USERNAME}
    password: ${REET_PLACE_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always

kakao:
  rest-api-key: ${REET_PLACE_LOCAL_KAKAO_API_KEY}

---
# Settings for production(dev-server)
logging:
  level:
    com.dnd.reetplace: info

spring:
  config.activate.on-profile: prod
  redis:
    host: ${REET_PLACE_PROD_REDIS_HOST}
    port: 6379
  datasource:
    url: ${REET_PLACE_PROD_DB_URL}
    username: ${REET_PLACE_PROD_DB_USERNAME}
    password: ${REET_PLACE_PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  sql.init.mode: never

kakao:
  rest-api-key: ${REET_PLACE_PROD_KAKAO_API_KEY}

jwt.secret: ${REET_PLACE_PROD_JWT_SECRET}

---
# Settings for test
spring:
  config.activate.on-profile: test
  redis:
    port: 10000
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always